### ISSUE TITLE
_isMockFunction

### ISSUE THREAD

**Issue by idahogurl** [microsoft/vscode-test#198]
## Description
Starting with VS Code 1.74.1, I get the following error when running tests using Jest. It works with VS Code 1.73.1
```
 Cannot find module '_isMockFunction'
    Require stack:
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
    - /Users/Rebecca.Vest/dev/vs-code-prettier-eslint/.vscode-test/vscode-darwin-arm64-1.74.1/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
   ```

## Reproduction
1. Clone https://www.github.com/vs-code-prettier-eslint
2. Run `yarn` to install node modules
3. Run `yarn test`

**Comment by connor4312** [comment]
This is caused by Jest trying to define a property on every global. Which is pretty questionable in a world where WeakSet 
 (and at _least_ Object.defineProperty) exists. That is then triggers a proxy getter and causing this error.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/2230985/221621157-e1bd2dca-c6bd-472a-a6d7-75c071221def.png">

@alexdima not sure if you want to do anything here
